export {default as AboutText} from './AboutText.vue'
export {default as Navbar} from './Navbar.vue'
export {default as SideBar} from './SideBar.vue'
export {default as TestimonialsModal} from './TestimonialsModal.vue'
export {default as Header} from './Header.vue'
export {default as Eyes} from './Eyes.vue'
export {default as Footer} from './Footer.vue'
export {default as Test} from './Test.vue'