export {default as AboutText} from './AboutText.vue'
export {default as Navbar} from './Navbar.vue'
export {default as SideBar} from './SideBar.vue'
export {default as TestTestimonialss} from './TestTestimonialss.vue'
export {default as TestimonialsModal} from './TestimonialsModal.vue'
export {default as Header} from './Header.vue'